### ISSUE TITLE
Feature Request: TextEncoder / TextDecoder

### ISSUE THREAD

**Issue by Menci** [Financial-Times/polyfill-library#554] opened 2020-03-28 06:26 UTC
## What
Seems polyfill.io doesn't support TextEncoder and TextDecoder.

## Details
https://developer.mozilla.org/zh-CN/docs/Web/API/TextEncoder

**Comment by JakeChampion** [comment] 2020-03-28 09:21
Duplicate of https://github.com/Financial-Times/polyfill-library/issues/207

**Closed by JakeChampion** 2020-03-28 09:21 UTC

**Comment by Menci** [comment] 2020-03-28 17:17
Oh no why I didn't see any issues when I search for TextEncoder.
