### ISSUE TITLE
[polyfill] queueMicrotask

### ISSUE THREAD

**Issue by FezVrasta** [Financial-Times/polyfill-library#402] opened 2020-01-25 19:02 UTC
## What

Could `queueMicrotask` get added to the supported polyfills? Chrome/Firefox/WebKit support it.

**Comment by JakeChampion** [comment] 2020-02-07 11:06
Duplicate of https://github.com/Financial-Times/polyfill-library/issues/303

**Closed by JakeChampion** 2020-02-07 11:06 UTC
