### ISSUE TITLE
Weekly tests with polyfill combinations are failing in IE8

### ISSUE THREAD

**Issue by romainmenke** [Financial-Times/polyfill-library#1129] opened 2021-11-24 16:01 UTC
see : https://github.com/Financial-Times/polyfill-library/runs/4280696106?check_suite_focus=true

```
Browser: ie/8.0 Test config: targeted / combined / shard 1   ✘ 610 tests, 46 failures  116 seconds to complete


Failures:
 - ie/8.0:
    -> TextEncoder passes the feature detect
       http://bs-local.com:9876/test?includePolyfills=yes&always=no&feature=TextEncoder
       false == true
 - ie/8.0:
    -> TextEncoder TextEncoder has a valid constructor
       http://bs-local.com:9876/test?includePolyfills=yes&always=no&feature=TextEncoder
       'TextEncoder' is undefined
 - ie/8.0:
    -> TextEncoder TextDecoder has a valid constructor
       http://bs-local.com:9876/test?includePolyfills=yes&always=no&feature=TextEncoder
       'TextDecoder' is undefined
 - ie/8.0:
    -> TextEncoder TextDecoder decodes encoded strings
       http://bs-local.com:9876/test?includePolyfills=yes&always=no&feature=TextEncoder
       'TextEncoder' is undefined
...
```

I can't immediately see which change introduced this regression.

There is an exception on : `polyfills/Object/defineProperty/polyfill.js:37`
This explains why polyfill tests fail at some point.
Something throws an exception, stopping execution of the polyfill bundle.

```js
if (!supportsAccessors) {
	throw new TypeError(ERR_ACCESSORS_NOT_SUPPORTED);
}
```

But there are a lot of callers and most have a `try catch`.

To reproduce manually in IE8 :

http://bs-local.com:9876/test?includePolyfills=yes&always=no&feature=WeakMap&polyfillCombinations=yes

**Comment by romainmenke** [comment] 2021-12-07 13:52
@JakeChampion I saw that you just released a [new version](https://github.com/Financial-Times/polyfill-library/releases/tag/v3.110.0).

Maybe you missed this issue, but I think one of the last updates broken a bunch of things in IE8. I haven't had time to look into more :/

**Comment by JakeChampion** [comment] 2021-12-07 14:05
You're right @romainmenke I did miss this - I'll see if I have time to look into it today - thank you for pinging me on this!

**Comment by JakeChampion** [comment] 2021-12-07 14:34
I'm looking into this now btw

**Comment by JakeChampion** [comment] 2021-12-07 14:52
It looks like the issue is possibly within the ArrayBuffer polyfill as that uses Object.defineProperty getters and setters without being within a try..catch block.

```js
// ES5: Make obj[index] an alias for obj._getter(index)/obj._setter(index, value)
  // for index in 0 ... obj.length
  function makeArrayAccessors(obj) {
    if ('TYPED_ARRAY_POLYFILL_NO_ARRAY_ACCESSORS' in global)
      return;

    if (obj.length > MAX_ARRAY_LENGTH) throw RangeError('Array too large for polyfill');

    function makeArrayAccessor(index) {
      Object.defineProperty(obj, index, {
        'get': function() { return obj._getter(index); },
        'set': function(v) { obj._setter(index, v); },
        enumerable: true,
        configurable: false
      });
    }

    var i;
    for (i = 0; i < obj.length; i += 1) {
      makeArrayAccessor(i);
    }
  }
```

**Comment by JakeChampion** [comment] 2021-12-07 16:25
I think I have now found the fix for this and also found another bug to fix :D

**Closed** 2021-12-08 18:54 UTC
Labels: library

**Comment by romainmenke** [comment] 2021-12-09 08:04
Thank you @JakeChampion for taking the time to track this down and getting it resolved so quickly!
