### ISSUE TITLE
IE11 - Unable to get property '@@__symbol:toStringTag0.1657645160586493312' of undefined or null reference

### ISSUE THREAD

**Issue by niftylettuce** [Financial-Times/polyfill-library#323] opened 2019-10-31 21:15 UTC
Error:

<img width="813" alt="Screen Shot 2019-10-31 at 4 14 10 PM" src="https://user-images.githubusercontent.com/523141/67986675-8cd97200-fbf9-11e9-9c84-a77fcf3254e2.png">

URL:

```html
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6,es7,Element,Element.prototype.append,Element.prototype.prepend,Element.prototype.replaceWith,Element.prototype.after,Element.prototype.before,Element.prototype.cloneNode,Element.prototype.classList,Element.prototype.matches,Element.prototype.dataset,Element.prototype.closest,Element.prototype.placeholder,Element.prototype.remove,Element.prototype.toggleAttribute,devicePixelRatio,Object.assign,Uint32Array,Reflect,fetch,Math.sign,Promise,Symbol,Symbol.iterator,Symbol.prototype,Symbol.toPrimitive,Symbol.toStringTag,Uint8Array,WeakMap">
```

cc @spence-s

**Comment by JakeChampion** [comment] 2020-04-20 00:47
duplicate of https://github.com/Financial-Times/polyfill-library/issues/163

**Closed by JakeChampion** 2020-04-20 00:47 UTC
Labels: bug, library
