### ISSUE TITLE
ArrayBuffer is polyfilled in browsers that support it

### ISSUE THREAD

**Issue by muster-mark** [Financial-Times/polyfill-library#1081] opened 2021-08-06 17:18 UTC
With the following URL in the latest version of both Firefox and Chrome, I see that polyfill.io thinks that the browsers require a polyfill for ArrayBuffer.

https://polyfill.io/v3/polyfill.min.js?features=ArrayBuffer

But according to caniuse.com, both browser have supported it fully for years (https://caniuse.com/mdn-javascript_builtins_arraybuffer).

Am I missing something?

**Comment by romainmenke** [comment] 2021-08-09 21:20
caused by : https://github.com/Financial-Times/polyfill-useragent-normaliser/blob/master/lib/normalise-user-agent.vcl#L1805

**Comment by JakeChampion** [comment] 2021-08-10 09:07
@romainmenke I can't quite follow how that line in the vcl is causing this issue, could you explain why that line is the cause?

**Comment by romainmenke** [comment] 2021-08-10 09:46
@JakeChampion sorry, confused this issue with the inverse case. Having a UA string with a very old browsers would result in all polyfills being included. Having old browsers in config works fine.

Just checked in the library and requesting `ArrayBuffer` with modern Chrome or Safari and the polyfill is not included.
So not sure what is going on. Sorry for the confusion :)

```js
	it('should not include ArrayBuffer on new Safari', async () => {
		const bundle = await polyfillLibrary.getPolyfillString({
			features: {
				ArrayBuffer: {}
			},
			uaString: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15',
		});

		console.log(bundle);
	});

		it('should not include ArrayBuffer on new Chrome', async () => {
		const bundle = await polyfillLibrary.getPolyfillString({
			features: {
				ArrayBuffer: {}
			},
			uaString: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36',
		});

		console.log(bundle);
	});
```

```
/* Polyfill service DEVELOPMENT MODE - for live use set NODE_ENV to 'production'
 * Disable minification (remove `.min` from URL path) for more info */


    ✓ should not include ArrayBuffer on new Safari
/* Polyfill service DEVELOPMENT MODE - for live use set NODE_ENV to 'production'
 * Disable minification (remove `.min` from URL path) for more info */


    ✓ should not include ArrayBuffer on new Chrome
```

**Comment by JakeChampion** [comment] 2021-08-10 13:57
Thanks @romainmenke!

@muster-mark, could you post some of the user-agent strings which are seeing this issue please?

**Comment by muster-mark** [comment] 2021-08-10 21:07
@JakeChampion Sure, here they are.

Firefox: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:90.0) Gecko/20100101 Firefox/90.0"
Chrome: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36"
Safari: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15"
Edge: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36 Edg/92.0.902.67"

**Comment by romainmenke** [comment] 2021-08-11 16:03
🤦 I could have checked this sooner.

This change hasn't been released yet on the polyfill-service

https://github.com/Financial-Times/polyfill-library/commit/ff90e8554a628e32ff2ce6318ecd528e38fddeb0#diff-46b8cfc7f1ad7813384be95dce8598b99339229acb5c08295d2e7f5c65b574c5

**Comment by romainmenke** [comment] 2021-09-15 06:07
This is fixed and released : 

https://polyfill.io/v3/polyfill.js?features=ArrayBuffer

```
/* Polyfill service v3.108.0
 * For detailed credits and licence information see https://github.com/financial-times/polyfill-service.
 * 
 * Features requested: ArrayBuffer
 *  */


/* No polyfills needed for current settings and browser */
```

**Closed** 2021-09-15 09:32 UTC
Labels: library
