### ISSUE TITLE
Broken source links on site

### ISSUE THREAD

**Issue by adamchainz** [Financial-Times/polyfill-library#1189] opened 2022-05-20 07:49 UTC
type: bug report

1. Go to https://polyfill.io/v3/url-builder/
2. Click "..." on `~html-elements` (near bottom)
3. Click "Polyfill source"
4. Link opens https://github.com/Financial-Times/polyfill-library/tree/main/polyfills/~viewport , which is 404 , because  the `main` branch doesn't exist. The real link is https://github.com/Financial-Times/polyfill-library/tree/master/polyfills/%7Ehtml5-elements .

Perhaps you mean to rename `master` to `main`?

I also noticed that `~viewport` has a source link, but it's not in the repo.

**Comment by esetnik** [comment] 2022-12-12 14:16
I just encountered the same issue. Looks like the website points to `main` but it's a non-existent branch in the repo.

**Comment by mhassan1** [comment] 2023-05-22 23:56
This is a duplicate of https://github.com/Financial-Times/polyfill-service/issues/2723.

**Closed by mhassan1** 2023-05-22 23:56 UTC
Labels: library
