### ISSUE TITLE
[BUG] Cannot modify non-writable property 'search'

### ISSUE THREAD

**Issue by mathieumagalhaes** [Financial-Times/polyfill-library#230] opened 2019-06-10 17:53 UTC
## What
Seeing multiple errors in our sentry monitoring setup.
"Cannot modify non-writable property 'search'"

## Details
Seeing "Cannot modify non-writable property 'search'" as an error on most Edge browser versions.

## Additional information
Polyfill service version: **v3**
**My polyfill service features:**
    'default',
    'es6',
    'Window',
    'console',
    'console.log',
    'console.info',
    'console.error',
    'console.warn',
    'console.debug',
    'setImmediate',
    'localStorage',
    'Event',
    'EventSource',
    'CustomEvent',
    'WeakSet',
    'WeakMap',
    'Promise',
    'classList',
    'document.querySelector',
    'requestAnimationFrame',
    'Element.prototype.placeholder',
    'Number.parseInt',
    'Number.parseFloat',
    'Number.isNaN',
    'Array.prototype.find',
    'Array.prototype.forEach',
    'Array.prototype.indexOf',
    'Object.values',
    'Object.entries',
    'Symbol.split',
    'Symbol.replace',
    'Symbol.match',
    'Symbol.iterator',

**Comment by mathieumagalhaes** [comment] 2019-07-03 23:10
Currently solved by changing the used features list to a specific list (no default/es6).

## What
But still seeing some errors once in a while:

## Details + Additional information
"**Attempting to change value of a readonly property**"
On Mobile Safari 9.0 browsers, on iPad (seen with iOS 9.3.5)

And "**Cannot convert a Symbol value to a string**"
Seen at line 3:28139 (/v3/polyfill.min.js)
On multiple platforms (android, iOS, windows, Mac)

**Comment by JakeChampion** [comment] 2019-07-04 10:35
Hi @mathieumagalhaes, sorry to see you are having some issues with the project.

Could you post some of the full user-agent strings you are seeing these errors on at all?

If you are using the polyfill-library directly, could you post all the parameter values you are using when generating a polyfill bundle?

If you are using the polyfill-service (polyfill.io), could you please post the full polyfill.io URL you are using?

Do these errors occur by running the polyfill bundle alone or when some specific JavaScript code on the page is also executing? If it doesn't occur by running the polyfill bundle alone, could you please post some JavaScript code that would cause the errors to occur :-)

With the information I've requested above, I should hopefully be in a much better place to help you find the cause of the issue and perhaps fix it :-)

**Comment by mathieumagalhaes** [comment] 2019-07-06 04:05
**I use the features above as follow:**

```
https://polyfill.io/v3/polyfill.min.js?callback=polyfillsLoadedFn&features=${POLYFILLS_FEATURES.join(',')
```

**Some user agents (multiple platform/browsers):**
```Mozilla/5.0 (iPad; CPU OS 9_3_5 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13G36 Safari/601.1```

```Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36```

```Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36```

```Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36```

```Mozilla/5.0 (Linux; U; Android 5.1; en-US; GN5001S Build/LMY47D) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/40.0.2214.89 UCBrowser/11.5.0.1015 Mobile Safari/537.36```

```Mozilla/5.0 (Windows NT 6.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36```

```Mozilla/5.0 (iPad; CPU OS 5_0 like Mac OS X) AppleWebKit/537.36 (KHTML, like Gecko) Version/5.1 Mobile/9A334 Safari/7534.48.3```

```Mozilla/5.0 (iPad; CPU OS 9_3_5 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13G36 Safari/601.1```

**These are the ones that caught the error:**
```
Cannot convert a Symbol value to a string
/v3/polyfill.min.js at line 3:29534
```

**Comment by JakeChampion** [comment] 2020-12-16 15:57
I can't replicate this error in any of those browsers anymore, I assume we must have fixed this at some point and not closed this issue

**Closed by JakeChampion** 2020-12-16 15:57 UTC
Labels: bug, library
