### ISSUE TITLE
Error in IE11

### ISSUE THREAD

**Issue by danielantelo** [Financial-Times/polyfill-library#267] opened 2019-03-29 16:52 UTC
## What
Possible bug with Object polyfills in IE11 (or maybe just poor configuration on our side?)

## Details
I've just replaced using `babel-polyfill` in our webpack setup with including the script `https://polyfill.js?flags=gated&features=default,es5,es6,es7,CustomEvent,IntersectionObserver` in our head. 

Sadly we seem to get an error in IE11. All other browser seem good.

![SC 2019-03-29 at 16 41 38](https://user-images.githubusercontent.com/9608393/55248431-b8e6dc00-5241-11e9-9960-90deb07a39ea.jpg)

![SC 2019-03-29 at 15 54 30](https://user-images.githubusercontent.com/9608393/55245468-1f1c3080-523b-11e9-9402-300184e15de0.jpg)

![SC 2019-03-29 at 16 37 51](https://user-images.githubusercontent.com/9608393/55248174-26ded380-5241-11e9-8063-fe01e0591e8c.jpg)

Any ideas?

**Comment by JakeChampion** [comment] 2020-04-20 00:44
duplicate of https://github.com/Financial-Times/polyfill-library/issues/115

**Closed by JakeChampion** 2020-04-20 00:44 UTC
Labels: bug, library
