### ISSUE TITLE
[feature-request] Add EventTarget polyfill

### ISSUE THREAD

**Issue by Vanilagy** [Financial-Times/polyfill-library#291] opened 2019-08-04 13:30 UTC
I think it would be awesome if you guys added a polyfill for EventTarget, as it is not available in Safari, yet is a vital component of any complex application I make.

Current workarounds include substituting EventTarget for Element, or including some polyfill, in which case I usually go for: https://github.com/ungap/event-target

**Comment by JakeChampion** [comment] 2020-02-26 15:02
duplicate of https://github.com/Financial-Times/polyfill-library/issues/252

**Closed by JakeChampion** 2020-02-26 15:02 UTC
